osdp:
  outputs:
    dev:
      host: spark-thrift-service.spark-apps.svc.cluster.local
      method: thrift
      port: 10000
      schema: restaurant
      threads: 4
      type: spark
  target: dev
